# This is a basic workflow to help you get started with Actions

name: Build and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: '3.7'
      - name: Download Splunk Packaging Toolkit
        run: wget -O spt.tar.gz 'https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz'
      - name: Install SPT
        run: pip install spt.tar.gz
      - name: Make artifacts dir
        run: mkdir out
      - name: SLIM Package App
        run: slim package $GITHUB_WORKSPACE/pii_tools
        working-directory: out/
      - name: List dir
        run: ls -lh; ls -lh out
#       - name: Get filename of app package
#         run: echo "package_filename=$(echo pii_tools*.tar.gz)" >> "$GITHUB_ENV"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "entire_dir"
          path: out/
#           path: "${{ env.package_filename }}"
